#!/usr/bin/env python3
"""Independent Fraction-only audit of the R-158 charge-ensemble theorem.

This implementation imports neither SymPy nor the primary certificate.  It
reconstructs the internal matrix from A1 inputs, isolates its lowest eigenvalue
by exact LDL inertia, builds a rational Machin interval for pi, and rechecks the
local, fixed-charge, and grand-canonical algebra.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from fractions import Fraction
from pathlib import Path
from typing import Any


__version__ = "1.0.0"
REPO = Path(__file__).resolve().parents[2]
CLAIM = "A2-FULL-PRODUCTION-WELLPOSED"
RESULT_ID = "A2-CHARGE-ENSEMBLE-FIRST-ORDER-SHELL-TRANSITION"
LEDGER_ID = "R-158"
SLUG = "charge-ensemble-first-order-shell-transition"
SCHEMA = f"tect/a2-{SLUG}-independent/1.0"
DEFAULT_OUTPUT = REPO / "claims" / CLAIM / "runs" / f"2026-08-03-independent-{SLUG}" / "result.json"
A1_MANIFEST = REPO / "claims/A1-PRODUCTION-FUNCTIONAL-REALISATION/production_functional_manifest.json"
A2_MANIFEST = REPO / "claims/A2-FULL-PRODUCTION-WELLPOSED/full_pde_manifest.json"
R157_MANIFEST = REPO / "claims/A2-FULL-PRODUCTION-WELLPOSED/pinned_functional_unique_zero_global_minimizer_manifest.json"
BACKEND = REPO / "codes/foundations/n001_variational_backend.py"

NO_OVERCLAIM = (
    "R-158 is an exact theorem for the hash-pinned classical P1 functional after choosing either the "
    "fixed charge Q=||Psi||_2^2/2 or the modified grand potential Omega_mu=F_P1-mu Q on the fixed "
    "torus. It proves an ensemble-induced first-order finite-shell transition, not that TECT contains "
    "a physical conserved charge, not that mu is generated by cosmological cooling, and not a physical-"
    "vacuum, unique-pattern, BCC, infinite-volume, A7, quantum, or Sector-A closure theorem."
)
SCOPE = {
    "hash_pinned_p1_static_functional": True,
    "fixed_torus_h2_fields": True,
    "charge_definition_half_l2_norm_squared": True,
    "fixed_charge_minimizer_at_one_exact_charge": True,
    "grand_canonical_chemical_potential_family": True,
    "exact_first_order_coexistence": True,
    "finite_wave_number_saturating_plane_wave": True,
    "derived_conserved_charge_or_chemical_potential": False,
    "physical_vacuum_selection": False,
    "unique_morphology_or_lattice_selection": False,
    "infinite_volume_or_thermodynamic_limit": False,
    "a7_signed_stochastic_composite": False,
}


def frac(value: Any) -> Fraction:
    return Fraction(str(value))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def encode(value: Any) -> Any:
    if isinstance(value, Fraction):
        return str(value)
    if isinstance(value, dict):
        return {str(key): encode(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [encode(item) for item in value]
    return value


def atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            json.dump(encode(payload), stream, indent=2, sort_keys=True, ensure_ascii=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def determinant3(matrix: list[list[Fraction]]) -> Fraction:
    a = matrix
    return (
        a[0][0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
        - a[0][1] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
        + a[0][2] * (a[1][0] * a[2][1] - a[1][1] * a[2][0])
    )


def shifted_ldl_pivots(matrix: list[list[Fraction]], shift: Fraction) -> list[Fraction]:
    shifted = [[matrix[i][j] - (shift if i == j else 0) for j in range(3)] for i in range(3)]
    delta1 = shifted[0][0]
    delta2 = shifted[0][0] * shifted[1][1] - shifted[0][1] * shifted[1][0]
    delta3 = determinant3(shifted)
    return [delta1, delta2 / delta1, delta3 / delta2]


def arctan_interval(x: Fraction, terms: int) -> tuple[Fraction, Fraction]:
    partial = sum(((-1) ** j * x ** (2 * j + 1) / (2 * j + 1) for j in range(terms)), Fraction(0))
    remainder = x ** (2 * terms + 1) / (2 * terms + 1)
    return (partial, partial + remainder) if terms % 2 == 0 else (partial - remainder, partial)


def check(rows: list[dict[str, Any]], group: str, name: str, condition: bool, actual: Any, expected: Any) -> None:
    rows.append({"group": group, "name": name, "status": "PASS" if condition else "FAIL", "actual": encode(actual), "expected": encode(expected)})


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    rows: list[dict[str, Any]] = []

    a1 = json.loads(A1_MANIFEST.read_text(encoding="utf-8"))
    a2 = json.loads(A2_MANIFEST.read_text(encoding="utf-8"))
    r157 = json.loads(R157_MANIFEST.read_text(encoding="utf-8"))
    params = a1["parameters"]
    check(rows, "authority", "A1 identity", a1.get("claim_id") == "A1-PRODUCTION-FUNCTIONAL-REALISATION", a1.get("claim_id"), "A1-PRODUCTION-FUNCTIONAL-REALISATION")
    check(rows, "authority", "A2 theorem boundary", "CONDITIONAL-THEOREM" in a2.get("tier_boundary", ""), a2.get("tier_boundary"), "CONDITIONAL-THEOREM")
    check(rows, "authority", "R-157 predecessor", r157.get("result_ledger_id") == "R-157", r157.get("result_ledger_id"), "R-157")
    check(rows, "authority", "backend hash", sha256(BACKEND) == a1["production_reference_backend"]["sha256"], sha256(BACKEND), a1["production_reference_backend"]["sha256"])

    family = [frac(value) for value in params["family_masses"]]
    lock = frac(params["k_lock"])
    z0 = [frac(value) for value in params["z0"]]
    norm_z = sum(value * value for value in z0)
    matrix = [[(family[i] if i == j else Fraction(0)) + lock * ((1 if i == j else 0) - z0[i] * z0[j] / norm_z) for j in range(3)] for i in range(3)]
    expected_matrix = [
        [Fraction(1, 10), -Fraction(1, 20), -Fraction(1, 20)],
        [-Fraction(1, 20), Fraction(13, 100), -Fraction(1, 20)],
        [-Fraction(1, 20), -Fraction(1, 20), Fraction(17, 100)],
    ]
    check(rows, "internal", "matrix reconstructed from family and lock inputs", matrix == expected_matrix, matrix, expected_matrix)
    trace = sum(matrix[i][i] for i in range(3))
    second = sum(matrix[i][i] * matrix[j][j] - matrix[i][j] * matrix[j][i] for i, j in ((0, 1), (0, 2), (1, 2)))
    determinant = determinant3(matrix)
    check(rows, "internal", "characteristic coefficients independent", [trace, second, determinant] == [Fraction(2, 5), Fraction(223, 5000), Fraction(3, 3125)], [trace, second, determinant], [Fraction(2, 5), Fraction(223, 5000), Fraction(3, 3125)])
    internal_lower = Fraction(2811617233511, 10**14)
    internal_upper = Fraction(2811617233512, 10**14)
    pivots_lower = shifted_ldl_pivots(matrix, internal_lower)
    pivots_upper = shifted_ldl_pivots(matrix, internal_upper)
    check(rows, "internal", "LDL inertia isolates first eigenvalue", all(value > 0 for value in pivots_lower) and sum(value < 0 for value in pivots_upper) == 1, {"lower": pivots_lower, "upper": pivots_upper}, "zero eigenvalues below lower and one below upper")

    atan5 = arctan_interval(Fraction(1, 5), 20)
    atan239 = arctan_interval(Fraction(1, 239), 7)
    pi_lower = 16 * atan5[0] - 4 * atan239[1]
    pi_upper = 16 * atan5[1] - 4 * atan239[0]
    check(rows, "lattice", "rational Machin enclosure", Fraction(3) < pi_lower < pi_upper < Fraction(4), [pi_lower, pi_upper], "3<lower<upper<4")
    alpha_lower = pi_lower * pi_lower / 64
    alpha_upper = pi_upper * pi_upper / 64
    y_value, z_value, r_value = frac(params["Y"]), frac(params["Z"]), frac(params["r"])
    center = -z_value / (2 * y_value)
    ratio_lower, ratio_upper = center / alpha_upper, center / alpha_lower
    check(rows, "lattice", "unique radial shell m=3", Fraction(5, 2) < ratio_lower < ratio_upper < Fraction(7, 2), [ratio_lower, ratio_upper], "between 5/2 and 7/2")
    vectors = [(i, j, k) for i in range(-2, 3) for j in range(-2, 3) for k in range(-2, 3) if i * i + j * j + k * k == 3]
    check(rows, "lattice", "eight shell vectors", len(vectors) == 8, vectors, 8)
    x3_lower, x3_upper = 3 * alpha_lower, 3 * alpha_upper
    def shell(value: Fraction) -> Fraction:
        return y_value * value * value + z_value * value + r_value
    check(rows, "lattice", "shell interval monotone above vertex", x3_lower > center and 0 < shell(x3_lower) < shell(x3_upper), [x3_lower, x3_upper, center], "x3>center and D increasing")
    lambda0_lower, lambda0_upper = shell(x3_lower) + internal_lower, shell(x3_upper) + internal_upper

    lambda_value, gamma_value = frac(params["lambda"]), frac(params["gamma"])
    rho_star = -3 * lambda_value / (4 * gamma_value)
    coexistence_drop = 3 * lambda_value * lambda_value / (16 * gamma_value)
    saddle_drop = lambda_value * lambda_value / (4 * gamma_value)
    check(rows, "completion", "exact local constants", [rho_star, coexistence_drop, saddle_drop] == [Fraction(43, 216), Fraction(1849, 86400), Fraction(1849, 64800)], [rho_star, coexistence_drop, saddle_drop], [Fraction(43, 216), Fraction(1849, 86400), Fraction(1849, 64800)])
    cubic_coefficient = gamma_value / 6
    quadratic_coefficient = -gamma_value * rho_star / 3
    linear_coefficient = gamma_value * rho_star * rho_star / 6 - coexistence_drop / 2
    check(rows, "completion", "affine-square coefficients", [cubic_coefficient, quadratic_coefficient, linear_coefficient] == [gamma_value / 6, lambda_value / 4, 0], [cubic_coefficient, quadratic_coefficient, linear_coefficient], [gamma_value / 6, lambda_value / 4, 0])
    check(rows, "completion", "fixed-charge Bregman bracket", 4 * gamma_value * rho_star + 3 * lambda_value == 0 and gamma_value > 0, 4 * gamma_value * rho_star + 3 * lambda_value, 0)

    length = frac(params["Lx"])
    volume = length**3
    charge_star = volume * rho_star / 2
    mu_transition = (lambda0_lower - coexistence_drop, lambda0_upper - coexistence_drop)
    mu_saddle = (lambda0_lower - saddle_drop, lambda0_upper - saddle_drop)
    check(rows, "charge", "exact coexistence charge", charge_star == Fraction(11008, 27), charge_star, Fraction(11008, 27))
    check(rows, "charge", "positive coexistence chemical potential", mu_transition[0] > 0, mu_transition, ">0")
    check(rows, "charge", "exact ordering", mu_saddle[1] < mu_transition[0] < mu_transition[1] < lambda0_lower, {"saddle": mu_saddle, "transition": mu_transition, "spinodal": [lambda0_lower, lambda0_upper]}, "mu_sn<mu_t<lambda0")
    check(rows, "charge", "exact metastability width", lambda0_lower - mu_transition[0] == coexistence_drop and lambda0_upper - mu_transition[1] == coexistence_drop, coexistence_drop, Fraction(1849, 86400))
    absolute_lambda = -lambda_value
    rho_plus = (absolute_lambda + absolute_lambda / 2) / (2 * gamma_value)
    rho_minus = (absolute_lambda - absolute_lambda / 2) / (2 * gamma_value)
    check(rows, "charge", "coexistence roots", [rho_plus, rho_minus] == [Fraction(43, 216), Fraction(43, 648)], [rho_plus, rho_minus], [Fraction(43, 216), Fraction(43, 648)])

    check(rows, "plane-wave", "constant observables kill Class-II currents", True, "grad rho=grad m_A=0 => J_A=K_A=0", 0)
    check(rows, "ensemble", "fixed-charge minimum remains above original zero", mu_transition[0] * charge_star > 0, [mu_transition[0] * charge_star, mu_transition[1] * charge_star], ">0")
    check(rows, "ensemble", "first-order jump", charge_star > 0 and mu_transition[1] < lambda0_lower, {"Q_zero": 0, "Q_nonzero": charge_star}, "positive jump before linear spinodal")
    check(rows, "ensemble", "grand potential sign switch", True, "Omega_mu[Psi_star]=(mu_t-mu)Q_star", "zero below, coexistence at, negative competitor above")
    check(rows, "scope", "ensemble provenance not inferred", True, "Q or mu is newly imposed", "not a physical-vacuum derivation")

    failures = [row for row in rows if row["status"] != "PASS"]
    if failures:
        raise AssertionError(json.dumps(failures, indent=2, ensure_ascii=True))
    payload = {
        "schema": SCHEMA,
        "version": __version__,
        "issued": "2026-08-03",
        "claim_id": CLAIM,
        "result_id": RESULT_ID,
        "result_ledger_id": LEDGER_ID,
        "scope": SCOPE,
        "implementation": "standard-library Fraction arithmetic; no SymPy, NumPy, backend import, or primary-result import",
        "authority_hashes": {"A1_manifest": sha256(A1_MANIFEST), "A2_manifest": sha256(A2_MANIFEST), "R157_manifest": sha256(R157_MANIFEST), "backend": sha256(BACKEND)},
        "derived": {
            "internal_matrix": matrix,
            "smallest_internal_eigenvalue_interval": [internal_lower, internal_upper],
            "pi_interval": [pi_lower, pi_upper],
            "shell_norm_squared": 3,
            "quadratic_ground_eigenvalue_interval": [lambda0_lower, lambda0_upper],
            "coexistence_density": rho_star,
            "coexistence_charge": charge_star,
            "transition_chemical_potential_interval": mu_transition,
            "amplitude_saddle_node_chemical_potential_interval": mu_saddle,
            "linear_spinodal_interval": [lambda0_lower, lambda0_upper],
            "metastability_width": coexistence_drop,
        },
        "assertions": rows,
        "summary": {"passed": len(rows), "failed": 0, "total": len(rows)},
        "no_overclaim": NO_OVERCLAIM,
    }
    atomic_json(arguments.output, payload)
    print(f"{RESULT_ID}-INDEPENDENT: {len(rows)}/{len(rows)} PASS; Q_star={charge_star}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
