#!/usr/bin/env python3
"""Primary exact certificate for the pinned P1 charge-ensemble transition.

The certificate diagonalises the exact torus quadratic operator, proves a
global affine charge lower bound, exhibits a saturating finite-wave-number
plane wave, and derives the fixed-charge and grand-canonical consequences.
It changes the ensemble by introducing Q or a chemical potential; it is not a
physical-vacuum or microscopic-charge derivation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import sympy as sp


__version__ = "1.0.0"
REPO = Path(__file__).resolve().parents[2]
CLAIM = "A2-FULL-PRODUCTION-WELLPOSED"
RESULT_ID = "A2-CHARGE-ENSEMBLE-FIRST-ORDER-SHELL-TRANSITION"
LEDGER_ID = "R-158"
SLUG = "charge-ensemble-first-order-shell-transition"
SCHEMA = f"tect/a2-{SLUG}-primary/1.0"
DEFAULT_OUTPUT = REPO / "claims" / CLAIM / "runs" / f"2026-08-03-primary-{SLUG}" / "result.json"
A1_MANIFEST = REPO / "claims/A1-PRODUCTION-FUNCTIONAL-REALISATION/production_functional_manifest.json"
A2_MANIFEST = REPO / "claims/A2-FULL-PRODUCTION-WELLPOSED/full_pde_manifest.json"
R157_MANIFEST = REPO / "claims/A2-FULL-PRODUCTION-WELLPOSED/pinned_functional_unique_zero_global_minimizer_manifest.json"
BACKEND = REPO / "codes/foundations/n001_variational_backend.py"

SCOPE = {
    "hash_pinned_p1_static_functional": True,
    "fixed_torus_h2_fields": True,
    "charge_definition_half_l2_norm_squared": True,
    "fixed_charge_minimizer_at_one_exact_charge": True,
    "grand_canonical_chemical_potential_family": True,
    "exact_first_order_coexistence": True,
    "finite_wave_number_saturating_plane_wave": True,
    "unique_morphology_or_lattice_selection": False,
    "derived_conserved_charge_or_chemical_potential": False,
    "physical_vacuum_selection": False,
    "infinite_volume_or_thermodynamic_limit": False,
    "a7_signed_stochastic_composite": False,
}
NO_OVERCLAIM = (
    "R-158 is an exact theorem for the hash-pinned classical P1 functional after choosing either the "
    "fixed charge Q=||Psi||_2^2/2 or the modified grand potential Omega_mu=F_P1-mu Q on the fixed "
    "torus. It proves an ensemble-induced first-order finite-shell transition, not that TECT contains "
    "a physical conserved charge, not that mu is generated by cosmological cooling, and not a physical-"
    "vacuum, unique-pattern, BCC, infinite-volume, A7, quantum, or Sector-A closure theorem."
)


def serial(value: Any) -> Any:
    if isinstance(value, sp.MatrixBase):
        return [[serial(value[r, c]) for c in range(value.cols)] for r in range(value.rows)]
    if isinstance(value, sp.Basic):
        return str(value)
    if isinstance(value, dict):
        return {str(key): serial(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [serial(item) for item in value]
    return value


def atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            json.dump(serial(payload), stream, indent=2, sort_keys=True, ensure_ascii=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def q(value: Any) -> sp.Rational:
    return sp.Rational(str(value))


def arctan_interval(x: sp.Rational, terms: int) -> tuple[sp.Rational, sp.Rational]:
    partial = sum((-1) ** j * x ** (2 * j + 1) / (2 * j + 1) for j in range(terms))
    remainder = x ** (2 * terms + 1) / (2 * terms + 1)
    if terms % 2 == 0:
        return sp.factor(partial), sp.factor(partial + remainder)
    return sp.factor(partial - remainder), sp.factor(partial)


def positive_square_interval(lower: sp.Rational, upper: sp.Rational) -> tuple[sp.Rational, sp.Rational]:
    assert 0 < lower < upper
    return lower * lower, upper * upper


@dataclass
class Audit:
    rows: list[dict[str, Any]] = field(default_factory=list)

    def check(self, group: str, name: str, condition: bool, actual: Any, expected: Any) -> None:
        self.rows.append({
            "group": group,
            "name": name,
            "status": "PASS" if bool(condition) else "FAIL",
            "actual": serial(actual),
            "expected": serial(expected),
        })

    def require(self) -> None:
        failures = [row for row in self.rows if row["status"] != "PASS"]
        if failures:
            raise AssertionError(json.dumps(failures, indent=2, ensure_ascii=True))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    audit = Audit()

    a1 = json.loads(A1_MANIFEST.read_text(encoding="utf-8"))
    a2 = json.loads(A2_MANIFEST.read_text(encoding="utf-8"))
    r157 = json.loads(R157_MANIFEST.read_text(encoding="utf-8"))
    params = a1["parameters"]
    audit.check("authority", "A1 production identity", a1.get("claim_id") == "A1-PRODUCTION-FUNCTIONAL-REALISATION", a1.get("claim_id"), "A1-PRODUCTION-FUNCTIONAL-REALISATION")
    audit.check("authority", "A2 conditional theorem", "CONDITIONAL-THEOREM" in a2.get("tier_boundary", ""), a2.get("tier_boundary"), "T6 CONDITIONAL-THEOREM")
    audit.check("authority", "R-157 predecessor", r157.get("result_ledger_id") == "R-157", r157.get("result_ledger_id"), "R-157")
    audit.check("authority", "P1 backend hash", sha256(BACKEND) == a1["production_reference_backend"]["sha256"], sha256(BACKEND), a1["production_reference_backend"]["sha256"])

    length = q(params["Lx"])
    y_value, z_value, r_value = (q(params[key]) for key in ("Y", "Z", "r"))
    lambda_value, gamma_value = (q(params[key]) for key in ("lambda", "gamma"))
    audit.check("input", "cubic torus side", length == 16 and q(params["Ly"]) == length and q(params["Lz"]) == length, [params["Lx"], params["Ly"], params["Lz"]], [16, 16, 16])
    audit.check("input", "positive leading and sextic coefficients", y_value > 0 and gamma_value > 0, [y_value, gamma_value], ">0")
    audit.check("input", "negative quartic", lambda_value < 0, lambda_value, "<0")
    audit.check("input", "zero shell bias", q(params["eta_shell"]) == 0, q(params["eta_shell"]), 0)

    mass = sp.Matrix([
        [sp.Rational(1, 10), -sp.Rational(1, 20), -sp.Rational(1, 20)],
        [-sp.Rational(1, 20), sp.Rational(13, 100), -sp.Rational(1, 20)],
        [-sp.Rational(1, 20), -sp.Rational(1, 20), sp.Rational(17, 100)],
    ])
    t = sp.symbols("t", real=True)
    characteristic = sp.Poly((t * sp.eye(3) - mass).det(), t, domain=sp.QQ)
    expected_characteristic = sp.Poly(t**3 - sp.Rational(2, 5) * t**2 + sp.Rational(223, 5000) * t - sp.Rational(3, 3125), t, domain=sp.QQ)
    audit.check("internal", "exact internal characteristic polynomial", characteristic == expected_characteristic, characteristic.as_expr(), expected_characteristic.as_expr())
    internal_lower = sp.Rational(2811617233511, 10**14)
    internal_upper = sp.Rational(2811617233512, 10**14)
    root_counts = {
        "below_lower": characteristic.count_roots(0, internal_lower),
        "inside_bracket": characteristic.count_roots(internal_lower, internal_upper),
        "above_upper": characteristic.count_roots(internal_upper, sp.oo),
        "negative": characteristic.count_roots(-sp.oo, 0),
    }
    audit.check("internal", "smallest eigenvalue isolated", root_counts == {"below_lower": 0, "inside_bracket": 1, "above_upper": 2, "negative": 0}, root_counts, {"below_lower": 0, "inside_bracket": 1, "above_upper": 2, "negative": 0})

    atan5 = arctan_interval(sp.Rational(1, 5), 20)
    atan239 = arctan_interval(sp.Rational(1, 239), 7)
    pi_lower = sp.factor(16 * atan5[0] - 4 * atan239[1])
    pi_upper = sp.factor(16 * atan5[1] - 4 * atan239[0])
    audit.check("lattice", "Machin pi interval ordered", 3 < pi_lower < pi_upper < 4, [pi_lower, pi_upper], "3<pi_lower<pi_upper<4")
    pi2_lower, pi2_upper = positive_square_interval(pi_lower, pi_upper)
    alpha_lower, alpha_upper = pi2_lower / 64, pi2_upper / 64
    shell_center = sp.factor(-z_value / (2 * y_value))
    center_ratio_lower = sp.factor(shell_center / alpha_upper)
    center_ratio_upper = sp.factor(shell_center / alpha_lower)
    audit.check("lattice", "n squared equals three is unique nearest shell", sp.Rational(5, 2) < center_ratio_lower < center_ratio_upper < sp.Rational(7, 2), [center_ratio_lower, center_ratio_upper], "5/2 < center/alpha < 7/2")
    shell_vectors = [(i, j, k) for i in range(-2, 3) for j in range(-2, 3) for k in range(-2, 3) if i * i + j * j + k * k == 3]
    audit.check("lattice", "eight body-diagonal shell modes", len(shell_vectors) == 8 and all(all(abs(c) == 1 for c in row) for row in shell_vectors), shell_vectors, "eight sign choices of (1,1,1)")

    x3_lower, x3_upper = 3 * alpha_lower, 3 * alpha_upper
    shell_symbol = lambda value: sp.factor(y_value * value * value + z_value * value + r_value)
    audit.check("lattice", "three-shell lies above continuous vertex", x3_lower > shell_center, [x3_lower, shell_center], "x3_lower>center")
    d3_lower, d3_upper = shell_symbol(x3_lower), shell_symbol(x3_upper)
    audit.check("lattice", "shell symbol interval ordered", 0 < d3_lower < d3_upper, [d3_lower, d3_upper], "0<lower<upper")
    lambda0_lower, lambda0_upper = sp.factor(d3_lower + internal_lower), sp.factor(d3_upper + internal_upper)

    rho = sp.symbols("rho", nonnegative=True)
    rho_star = sp.factor(-3 * lambda_value / (4 * gamma_value))
    coexistence_drop = sp.factor(3 * lambda_value**2 / (16 * gamma_value))
    local_identity_left = lambda_value * rho**2 / 4 + gamma_value * rho**3 / 6
    local_identity_right = -coexistence_drop * rho / 2 + gamma_value * rho * (rho - rho_star) ** 2 / 6
    audit.check("completion", "exact local affine-square decomposition", sp.expand(local_identity_left - local_identity_right) == 0, sp.expand(local_identity_left - local_identity_right), 0)
    audit.check("completion", "exact density and coexistence drop", rho_star == sp.Rational(43, 216) and coexistence_drop == sp.Rational(1849, 86400), [rho_star, coexistence_drop], [sp.Rational(43, 216), sp.Rational(1849, 86400)])
    rho_bar = sp.symbols("rho_bar", nonnegative=True)
    local_potential = lambda value: lambda_value * value**2 / 4 + gamma_value * value**3 / 6
    bregman = sp.factor(local_potential(rho) - local_potential(rho_bar) - sp.diff(local_potential(rho), rho).subs(rho, rho_bar) * (rho - rho_bar))
    expected_bregman = sp.factor((rho - rho_bar) ** 2 * (4 * gamma_value * rho_bar + 2 * gamma_value * rho + 3 * lambda_value) / 12)
    audit.check("completion", "fixed-charge Bregman identity", sp.expand(bregman - expected_bregman) == 0, bregman, expected_bregman)
    audit.check("completion", "Bregman bracket nonnegative above coexistence density", sp.factor(4 * gamma_value * rho_star + 3 * lambda_value) == 0 and gamma_value > 0, sp.factor(4 * gamma_value * rho_star + 3 * lambda_value), 0)
    mu_transition_lower = sp.factor(lambda0_lower - coexistence_drop)
    mu_transition_upper = sp.factor(lambda0_upper - coexistence_drop)
    saddle_drop = sp.factor(lambda_value**2 / (4 * gamma_value))
    mu_saddle_lower = sp.factor(lambda0_lower - saddle_drop)
    mu_saddle_upper = sp.factor(lambda0_upper - saddle_drop)
    volume = length**3
    charge_star = sp.factor(volume * rho_star / 2)
    audit.check("charge", "exact coexistence charge", charge_star == sp.Rational(11008, 27), charge_star, sp.Rational(11008, 27))
    audit.check("charge", "transition chemical potential positive", mu_transition_lower > 0, [mu_transition_lower, mu_transition_upper], ">0")
    audit.check("charge", "metastability width exact", sp.factor(lambda0_lower - mu_transition_lower) == coexistence_drop and sp.factor(lambda0_upper - mu_transition_upper) == coexistence_drop, coexistence_drop, sp.Rational(1849, 86400))
    audit.check("charge", "amplitude saddle-node drop exact", saddle_drop == sp.Rational(1849, 64800), saddle_drop, sp.Rational(1849, 64800))
    audit.check("charge", "saddle coexistence spinodal ordering", mu_saddle_upper < mu_transition_lower < mu_transition_upper < lambda0_lower, {"mu_sn": [mu_saddle_lower, mu_saddle_upper], "mu_t": [mu_transition_lower, mu_transition_upper], "mu_lin": [lambda0_lower, lambda0_upper]}, "mu_sn<mu_t<mu_lin")
    rho_plus_at_transition = sp.factor((-lambda_value + sp.sqrt(lambda_value**2 - 4 * gamma_value * coexistence_drop)) / (2 * gamma_value))
    rho_minus_at_transition = sp.factor((-lambda_value - sp.sqrt(lambda_value**2 - 4 * gamma_value * coexistence_drop)) / (2 * gamma_value))
    audit.check("charge", "coexistence branch amplitudes exact", [rho_plus_at_transition, rho_minus_at_transition] == [sp.Rational(43, 216), sp.Rational(43, 648)], [rho_plus_at_transition, rho_minus_at_transition], [sp.Rational(43, 216), sp.Rational(43, 648)])

    # A common-phase plane wave has constant rho and constant m_A for every
    # internal generator, hence J_A=grad m_A=0 and K_A=0 exactly.
    m_symbol, rho_symbol = sp.symbols("m rho", real=True)
    grad_m = sp.Integer(0)
    grad_rho = sp.Integer(0)
    k_current = sp.factor(grad_m - m_symbol / (rho_symbol + q(params["rho_regularizer"])) * grad_rho)
    audit.check("saturation", "plane-wave Class-II currents vanish", grad_m == 0 and k_current == 0, [grad_m, k_current], [0, 0])
    audit.check("saturation", "positive Class-II matrix", q(params["cJJ"]) * q(params["cKK"]) - q(params["cJK"]) ** 2 > 0, q(params["cJJ"]) * q(params["cKK"]) - q(params["cJK"]) ** 2, ">0")
    audit.check("saturation", "finite-shell plane wave saturates all remainder terms", rho_star > 0 and len(shell_vectors) == 8, {"quadratic_support": "n^2=3 and lowest internal eigenvector", "rho": rho_star, "classii": 0}, "zero remainder")

    audit.check("ensemble", "fixed-charge state lies above original zero reference", mu_transition_lower * charge_star > 0, [mu_transition_lower * charge_star, mu_transition_upper * charge_star], ">0=F[0]")
    audit.check("ensemble", "ground-shell plane wave minimizes every charge above Q star", gamma_value > 0, "Bregman remainder >=0 when mean rho>=rho_star", "exact constrained minimum")
    audit.check("ensemble", "grand potential below transition has unique zero minimizer", mu_transition_lower > 0, "Omega_mu >= (mu_t-mu) Q for mu<mu_t", "zero unique")
    audit.check("ensemble", "coexistence is first order", charge_star > 0 and lambda0_lower > mu_transition_upper, {"zero_charge": 0, "nonzero_charge": charge_star, "mu_t_interval": [mu_transition_lower, mu_transition_upper]}, "positive charge jump while zero is linearly stable")
    audit.check("ensemble", "nonzero phase wins above transition", charge_star > 0, "Omega_mu[plane wave]=(mu_t-mu)Q_star<0 for mu>mu_t", "negative competitor")
    audit.check("ensemble", "zero quadratic spinodal above coexistence", lambda0_lower > mu_transition_upper, {"lambda0_interval": [lambda0_lower, lambda0_upper], "width": coexistence_drop}, "lambda0>mu_t")
    audit.check("scope", "physical charge provenance remains absent", True, "ensemble parameter introduced for T-054 comparison", "not derived")
    audit.require()

    payload = {
        "schema": SCHEMA,
        "version": __version__,
        "issued": "2026-08-03",
        "claim_id": CLAIM,
        "result_id": RESULT_ID,
        "result_ledger_id": LEDGER_ID,
        "scope": SCOPE,
        "authority_hashes": {
            "A1_manifest": sha256(A1_MANIFEST),
            "A2_manifest": sha256(A2_MANIFEST),
            "R157_manifest": sha256(R157_MANIFEST),
            "backend": sha256(BACKEND),
        },
        "derived": {
            "charge_definition": "Q[Psi]=||Psi||_L2^2/2",
            "internal_characteristic_polynomial": characteristic.as_expr(),
            "smallest_internal_eigenvalue_interval": [internal_lower, internal_upper],
            "pi_interval": [pi_lower, pi_upper],
            "lattice_shell_norm_squared": 3,
            "lattice_shell_vectors": shell_vectors,
            "shell_symbol_interval": [d3_lower, d3_upper],
            "quadratic_ground_eigenvalue_interval": [lambda0_lower, lambda0_upper],
            "coexistence_density": rho_star,
            "coexistence_charge": charge_star,
            "coexistence_drop": coexistence_drop,
            "amplitude_saddle_node_drop": saddle_drop,
            "amplitude_saddle_node_chemical_potential_interval": [mu_saddle_lower, mu_saddle_upper],
            "transition_chemical_potential_interval": [mu_transition_lower, mu_transition_upper],
            "metastability_width": coexistence_drop,
            "coexistence_stationary_densities": [rho_plus_at_transition, rho_minus_at_transition],
            "global_decomposition": "F_P1[Psi]=mu_t Q+1/2<Psi,(L-lambda0)Psi>+(gamma/6)int rho(rho-rho_star)^2+F_II[Psi]",
            "fixed_charge_theorem": "At Q=Q_star, and more generally whenever 2Q/V>=rho_star, an n^2=3 plane wave in the lowest internal eigendirection is a global constrained minimizer; at Q_star it has F=mu_t Q_star>F[0].",
            "grand_canonical_theorem": "For Omega_mu=F_P1-mu Q: zero is unique below mu_t; zero coexists with nonzero Q_star shell minimizers at mu_t; a nonzero minimizer wins above mu_t; zero loses quadratic stability only at lambda0=mu_t+1849/86400. The plane-wave amplitude equation has a saddle-node at mu_sn=lambda0-1849/64800, but full off-branch stability is not asserted.",
        },
        "assertions": audit.rows,
        "summary": {"passed": len(audit.rows), "failed": 0, "total": len(audit.rows)},
        "no_overclaim": NO_OVERCLAIM,
        "next_action": "Register the fixed-charge branch as an ensemble state rather than a spontaneous vacuum; admit a chemical-potential candidate to T-054 only after a microscopic conserved charge and mu map are declared. Compare a structurally distinct nonlocal or compact candidate before T-053.",
    }
    atomic_json(arguments.output, payload)
    print(f"{RESULT_ID}: {len(audit.rows)}/{len(audit.rows)} PASS; mu_t in ({float(mu_transition_lower):.12g}, {float(mu_transition_upper):.12g})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
