#!/usr/bin/env python3
"""Exact finite-step support audit for the Q3 onsite-plus-all-bond split.

The calculation is algebraic.  It records the closed-neighbourhood support
map generated by the all-bond configuration kick and keeps the existence of
the site-local onsite flow as an explicit hypothesis.  It does not estimate
operator norms or take the Trotter-count limit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from collections import deque
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[2]
SCRIPT = Path(__file__).resolve()
SLUG = "pre-a-cp1-st8-q3lock-finite-step-support-locality"
MANIFEST = REPO / f"strategy/{SLUG}-manifest.json"
DEFAULT_OUTPUT = REPO / "claims/C6-SPACETIME-SIGNATURE/runs" / f"2026-08-26-primary-{SLUG}" / "primary.json"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")).hexdigest()


def atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            json.dump(payload, stream, indent=2, sort_keys=True, ensure_ascii=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


class Audit:
    def __init__(self) -> None:
        self.rows: list[dict[str, Any]] = []

    def check(self, name: str, condition: bool, actual: Any, expected: Any, group: str) -> None:
        if not condition:
            raise AssertionError(f"{name}: actual={actual!r}, expected={expected!r}")
        self.rows.append({"name": name, "group": group, "status": "PASS", "actual": actual, "expected": expected})


def graph_edges(graph: dict[str, Any]) -> tuple[tuple[int, int], ...]:
    return tuple(sorted((min(int(left), int(right)), max(int(left), int(right))) for left, right in graph["edges"]))


def adjacency(graph: dict[str, Any]) -> dict[int, tuple[int, ...]]:
    vertices = range(int(graph["vertices"]))
    neighbors: dict[int, set[int]] = {vertex: set() for vertex in vertices}
    for left, right in graph_edges(graph):
        neighbors[left].add(right)
        neighbors[right].add(left)
    return {vertex: tuple(sorted(values)) for vertex, values in neighbors.items()}


def closed_neighborhood(graph: dict[str, Any], support: set[int]) -> set[int]:
    neighbors = adjacency(graph)
    return support | {neighbor for vertex in support for neighbor in neighbors[vertex]}


def iterate_neighborhood(graph: dict[str, Any], source: set[int], steps: int) -> list[set[int]]:
    trajectory = [set(source)]
    current = set(source)
    for _ in range(steps):
        current = closed_neighborhood(graph, current)
        trajectory.append(set(current))
    return trajectory


def distances(graph: dict[str, Any], source: set[int]) -> dict[int, int]:
    neighbors = adjacency(graph)
    result = {vertex: 10**9 for vertex in range(int(graph["vertices"]))}
    queue: deque[int] = deque()
    for vertex in sorted(source):
        result[vertex] = 0
        queue.append(vertex)
    while queue:
        vertex = queue.popleft()
        for neighbor in neighbors[vertex]:
            if result[neighbor] > result[vertex] + 1:
                result[neighbor] = result[vertex] + 1
                queue.append(neighbor)
    return result


def ball_vertices(graph: dict[str, Any], source: set[int], radius: int) -> set[int]:
    return {vertex for vertex, distance in distances(graph, source).items() if distance <= radius}


def induced_edges(graph: dict[str, Any], vertices: set[int]) -> tuple[tuple[int, int], ...]:
    return tuple(edge for edge in graph_edges(graph) if edge[0] in vertices and edge[1] in vertices)


def rooted_mapping_isomorphism(left: dict[str, Any], right: dict[str, Any], source: set[int], radius: int, mapping: dict[int, int]) -> bool:
    left_ball = ball_vertices(left, source, radius)
    right_ball = ball_vertices(right, {mapping[vertex] for vertex in source}, radius)
    if set(mapping) != left_ball or set(mapping.values()) != right_ball:
        return False
    left_dist = distances(left, source)
    right_dist = distances(right, {mapping[vertex] for vertex in source})
    if any(left_dist[vertex] != right_dist[mapping[vertex]] for vertex in left_ball):
        return False
    mapped_edges = tuple(sorted((min(mapping[u], mapping[v]), max(mapping[u], mapping[v])) for u, v in induced_edges(left, left_ball)))
    return mapped_edges == induced_edges(right, right_ball)


def kick_formula(graph: dict[str, Any]) -> dict[str, Any]:
    neighbors = adjacency(graph)
    return {
        "q_image": "q_x",
        "p_images": {str(vertex): {"p_x": 1, "neighbor_q_coefficient": "delta*c", "neighbors": list(neighbors[vertex])} for vertex in neighbors},
        "second_commutator": "0",
        "bond_factorization": len(graph_edges(graph)),
    }


def run() -> dict[str, Any]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    fixture = manifest["fixture"]
    graphs: dict[str, dict[str, Any]] = fixture["graphs"]
    audit = Audit()
    audit.check("identity", manifest["exploration_id"] == "EXP-001167" and manifest["task_id"] == "T-054", [manifest["exploration_id"], manifest["task_id"]], "EXP-001167/T-054", "provenance")
    audit.check("claim nonbearing", manifest["claim_bearing"] is False, manifest["claim_bearing"], False, "scope")
    audit.check("time signs", sorted(fixture["time_signs"]) == [-1, 1], sorted(fixture["time_signs"]), [-1, 1], "scope")
    audit.check("term orders", len(fixture["term_orders"]) == 2, fixture["term_orders"], "two orders", "scope")

    graph_rows: list[dict[str, Any]] = []
    for name, graph in graphs.items():
        edges = graph_edges(graph)
        vertices = int(graph["vertices"])
        audit.check(f"{name} edge validity", all(0 <= u < vertices and 0 <= v < vertices and u != v for u, v in edges), edges, "simple finite graph", "graph")
        audit.check(f"{name} edge uniqueness", len(edges) == len(set(edges)), len(edges), "unique", "graph")
        audit.check(f"{name} kick second commutator", kick_formula(graph)["second_commutator"] == "0", kick_formula(graph)["second_commutator"], "0", "BCH")
        audit.check(f"{name} factor count", kick_formula(graph)["bond_factorization"] == len(edges), kick_formula(graph)["bond_factorization"], len(edges), "BCH")
        for source_values in graph["sources"]:
            source = {int(value) for value in source_values}
            trajectory = iterate_neighborhood(graph, source, max(int(value) for value in graph["steps"]))
            distance = distances(graph, source)
            for steps in (int(value) for value in graph["steps"]):
                support = trajectory[steps]
                expected = ball_vertices(graph, source, steps)
                audit.check(f"{name} source={sorted(source)} N={steps} inclusion", support <= expected, sorted(support), sorted(expected), "support")
                audit.check(f"{name} source={sorted(source)} N={steps} envelope", support == expected, sorted(support), sorted(expected), "support")
                audit.check(f"{name} source={sorted(source)} N={steps} distance", all(distance[vertex] <= steps for vertex in support), {str(vertex): distance[vertex] for vertex in sorted(support)}, f"<= {steps}", "support")
                for sign in fixture["time_signs"]:
                    for order in fixture["term_orders"]:
                        signed = iterate_neighborhood(graph, source, steps)[-1]
                        audit.check(f"{name} source={sorted(source)} N={steps} sign={sign} order={order}", signed == support, sorted(signed), sorted(support), "split")
            graph_rows.append({"graph": name, "source": sorted(source), "trajectory": [sorted(row) for row in trajectory], "distances": {str(vertex): distance[vertex] for vertex in sorted(distance)}})

    equivalence = fixture["shape_equivalence"]
    left = graphs[equivalence["left"]]
    right = graphs[equivalence["right"]]
    source = {int(value) for value in equivalence["source"]}
    radius = int(equivalence["steps"])
    mapping = {int(key): int(value) for key, value in equivalence["mapping"].items()}
    audit.check("rooted ball isomorphism", rooted_mapping_isomorphism(left, right, source, radius, mapping), mapping, "rooted induced-ball isomorphism", "shape")
    left_trajectory = iterate_neighborhood(left, source, radius)
    right_trajectory = iterate_neighborhood(right, {mapping[value] for value in source}, radius)
    for step in range(radius + 1):
        mapped = {mapping[value] for value in left_trajectory[step]}
        audit.check(f"shape trajectory step={step}", mapped == right_trajectory[step], sorted(mapped), sorted(right_trajectory[step]), "shape")

    passed = len(audit.rows)
    return {
        "schema": "tect/foundation-audit/1.0",
        "run_kind": "primary",
        "verdict": "PASS",
        "passed": passed,
        "total": passed,
        "failed": 0,
        "assertions": audit.rows,
        "graph_rows": graph_rows,
        "shape_equivalence": {"left": equivalence["left"], "right": equivalence["right"], "source": sorted(source), "steps": radius, "mapping": mapping},
        "derived": {
            "all_bond_commuting_factorization_closed": True,
            "exact_qp_kick_closed": True,
            "onsite_support_preservation_conditional": True,
            "one_step_support_inclusion_closed": True,
            "N_step_support_inclusion_closed": True,
            "rooted_N_ball_shape_independence_closed": True,
            "finite_N_exhaustion_locality_closed": True,
            "analytic_trotter_rate_closed": False,
            "uniform_graph_lipschitz_closed": False,
            "common_core_domain_closed": False,
            "direct_d_delta_d_cauchy_closed": False,
            "N_to_infinity_common_alpha_closed": False,
            "exhaustion_independence_closed": False,
            "hamiltonian_os_identification_closed": False,
            "kms_gns_gap_closed": False,
            "continuum_closed": False,
            "c6_closed": False,
            "sector_a_closed": False,
            "pre_a_closed": False,
        },
        "provenance": {
            "script": str(SCRIPT.relative_to(REPO)).replace("\\", "/"),
            "script_sha256": sha256(SCRIPT),
            "manifest": str(MANIFEST.relative_to(REPO)).replace("\\", "/"),
            "manifest_sha256": sha256(MANIFEST),
        },
        "exploration_id": manifest["exploration_id"],
        "boundary": manifest["boundary"],
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    payload = run()
    if not args.self_test:
        atomic_json(args.output if args.output.is_absolute() else REPO / args.output, payload)
    print(f"PRIMARY FINITE-STEP-SUPPORT-LOCALITY PASS {payload['passed']}/{payload['total']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
