#!/usr/bin/env python3
"""build_dossier.py -- generated per-sector dossiers.

For each TOE sector A-F it emits theory/sectors/<X>.md gathering, BY REFERENCE
(no physical move; the orthogonal top-level trees are preserved):
  * the hand-written synthesis README (theory/sector-<X>-*/README.md),
  * the sector's claims with tier / named hypotheses / open gates,
  * the predictions whose claim-link is in the sector,
  * the negative results that reference a claim in the sector.
theory/sectors/INDEX.md is the one-screen sector scorecard.

These files are GENERATED -- never hand-edit. release_check runs
`build_dossier.py --check`; the catalog includes the output.

Usage:
  python verification/scripts/build_dossier.py [--check]

Changelog:
  1.0.0 (2026-06-09) first issue. Generated sector dossiers (folder-structure
        increment 2: gather-by-reference instead of physical nesting).
"""
__version__ = "1.0.0"

import argparse, json, os, re, sys, tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "theory" / "sectors"
SECTORS = ["A", "B", "C", "D", "E", "F"]
CLAIM_RE = re.compile(r"\b([A-F]\d+[A-Z]?-[A-Z0-9][A-Z0-9-]{2,})\b")
TIER_ORDER = ["T7", "T6", "T5", "T4", "T3", "T2", "T1", "T0"]


def atomic_write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent)); os.close(fd)
    Path(tmp).write_text(text, encoding="utf-8")
    os.replace(tmp, str(path))


def pipe(s):
    return str(s).replace("|", "\\|")


def load_claims():
    out = {s: [] for s in SECTORS}
    for d in sorted((REPO / "claims").iterdir()):
        sj = d / "status.json"
        if not d.is_dir() or d.name.startswith("_") or not sj.exists():
            continue
        c = json.loads(sj.read_text(encoding="utf-8"))
        s = c.get("sector")
        if s in out:
            out[s].append((d.name, c))
    return out


def sector_meta(s):
    for d in sorted((REPO / "theory").glob(f"sector-{s}-*")):
        rd = d / "README.md"
        parts = d.name.split("-", 2)
        name = parts[2] if len(parts) >= 3 else d.name
        role = ""
        if rd.exists():
            for ln in rd.read_text(encoding="utf-8").splitlines():
                t = ln.strip()
                if t and not t.startswith("#"):
                    role = t
                    break
            return name, role, str(rd.relative_to(REPO)).replace("\\", "/")
    return "", "", None


def load_predictions():
    f = REPO / "predictions" / "prediction-ledger.md"
    rows = {s: [] for s in SECTORS}
    if not f.exists():
        return rows
    for ln in f.read_text(encoding="utf-8").splitlines():
        if not ln.startswith("|"):
            continue
        cells = [c.strip() for c in ln.strip().strip("|").split("|")]
        if len(cells) < 6 or cells[0] in ("Prediction ID", "") or set(cells[0]) <= set("-: "):
            continue
        link = cells[5]
        m = CLAIM_RE.search(link)
        if m and m.group(1)[0] in rows:
            rows[m.group(1)[0]].append(dict(pid=cells[0], qty=cells[1], out=cells[3],
                                            status=cells[4], claim=m.group(1)))
    return rows


SEC_REF_RE = re.compile(r"\b([A-F]\d+)")


def load_negatives(prefix2sector):
    """Parse the registry; assign each row to sectors via actual claim prefixes
    (B1, B5, C5, ...) so bare references like '(B1)' are caught precisely."""
    f = REPO / "negative-results" / "registry.md"
    out = []
    if not f.exists():
        return out
    for ln in f.read_text(encoding="utf-8").splitlines():
        if not ln.startswith("| "):
            continue
        cells = [c.strip() for c in ln.strip().strip("|").split("|")]
        if len(cells) < 5 or cells[0] in ("Tag", "") or set(cells[0]) <= set("-: "):
            continue
        tag = cells[0]
        if not re.match(r"^(R|F|NG|AUDIT)-", tag):
            continue
        rowtext = " ".join(cells)
        claims = sorted(set(CLAIM_RE.findall(rowtext)))
        refs = {m.group(1) for m in SEC_REF_RE.finditer(rowtext)}
        refs |= {c.split("-", 1)[0] for c in claims}
        sectors = sorted({prefix2sector[r] for r in refs if r in prefix2sector})
        out.append(dict(tag=tag, branch=cells[1], mode=cells[2], claims=claims, sectors=sectors))
    return out


def tier_hist(claims):
    h = {}
    for _, c in claims:
        h[c.get("tier", "?")] = h.get(c.get("tier", "?"), 0) + 1
    return " ".join(f"{t}x{h[t]}" for t in TIER_ORDER if h.get(t)) or "-"


def render_sector(s, claims, preds, negs):
    name, role, readme = sector_meta(s)
    L = [f"# Sector {s} — {name} (dossier)", "",
         "> GENERATED by `verification/scripts/build_dossier.py` — do not hand-edit. "
         "Gathers the sector's claims, predictions, and negative results by reference; "
         "the orthogonal trees (`claims/`, `theory/`, `predictions/`, `negative-results/`) "
         "are unchanged.", ""]
    if role:
        L += [f"**Role.** {role}", ""]
    if readme:
        L += [f"**Synthesis:** [`{readme}`]({_rel(readme)})", ""]
    # claims
    L += ["## Claims", "", f"Tier profile: {tier_hist(claims)}", "",
          "| Claim | Tier | Named hypotheses | Open gates | Title |",
          "|---|---|---|---|---|"]
    for cid, c in sorted(claims):
        hyp = ", ".join(c.get("hypotheses", [])) or "—"
        gates = ", ".join(c.get("open_gates", [])) or "—"
        L.append(f"| [`{cid}`](../../claims/{cid}/INDEX.md) | {c.get('tier','?')} | "
                 f"{pipe(hyp)} | {pipe(gates)} | {pipe(c.get('title','')[:80])} |")
    # aggregate gates/hypotheses
    allhyp = sorted({h for _, c in claims for h in c.get("hypotheses", [])})
    allg = sorted({g for _, c in claims for g in c.get("open_gates", [])})
    L += ["", f"**Open named hypotheses (sector union):** {', '.join(allhyp) or '—'}  ",
          f"**Open gates (sector union):** {', '.join(allg) or '—'}", ""]
    # predictions
    L += ["## Predictions", ""]
    if preds:
        L += ["| Prediction | Quantity | Output | Status | Claim |", "|---|---|---|---|---|"]
        for p in preds:
            L.append(f"| {pipe(p['pid'])} | {pipe(p['qty'])} | {pipe(p['out'])} | "
                     f"{pipe(p['status'])} | [`{p['claim']}`](../../claims/{p['claim']}/INDEX.md) |")
    else:
        L += ["_None linked to this sector._"]
    L += [""]
    # negatives
    sec_negs = [n for n in negs if s in n["sectors"]]
    L += ["## Negative results (trust assets)", ""]
    if sec_negs:
        L += ["| Tag | Branch / claim | Failure mode |", "|---|---|---|"]
        for n in sec_negs:
            L.append(f"| {pipe(n['tag'])} | {pipe(n['branch'][:60])} | {pipe(n['mode'][:140])} |")
    else:
        L += ["_None referencing this sector's claims._"]
    L += ["", "---", "",
          "Reproduction: `python verification/scripts/build_dossier.py` · "
          "Source of truth: the linked claim cards, `predictions/prediction-ledger.md`, "
          "`negative-results/registry.md`.", ""]
    return "\n".join(L)


def _rel(repo_rel_path):
    # link target relative to theory/sectors/
    return "../../" + repo_rel_path


def render_index(claims_by_sector, preds, negs):
    L = ["# Sector dossiers — TOE scorecard", "",
         "> GENERATED by `verification/scripts/build_dossier.py` — do not hand-edit.", "",
         "One row per TOE sector. Each dossier gathers that sector's claims, predictions, "
         "and negative results by reference (no physical move; the orthogonal trees are "
         "preserved). This is the per-sector entry point alongside the top-down "
         "[`claims/INDEX.md`](../../claims/INDEX.md).", "",
         "| Sector | Theme | Claims | Tier profile | Open gates | Predictions |",
         "|---|---|---|---|---|---|"]
    for s in SECTORS:
        cl = claims_by_sector[s]
        name, role, _ = sector_meta(s)
        gates = sorted({g for _, c in cl for g in c.get("open_gates", [])})
        L.append(f"| [{s}]({s}.md) | {pipe(name)} | {len(cl)} | {tier_hist(cl)} | "
                 f"{len(gates)} | {len(preds.get(s, []))} |")
    L += ["", "Tier vocabulary: `governance/tier-system.md`. "
          "Generated-surface policy: `governance/sector-dossier.md`.", ""]
    return "\n".join(L)


def build():
    claims = load_claims()
    preds = load_predictions()
    prefix2sector = {cid.split("-", 1)[0]: s for s in SECTORS for cid, _ in claims[s]}
    negs = load_negatives(prefix2sector)
    files = {}
    for s in SECTORS:
        files[OUT / f"{s}.md"] = render_sector(s, claims[s], preds.get(s, []), negs)
    files[OUT / "INDEX.md"] = render_index(claims, preds, negs)
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    files = build()
    if args.check:
        stale = [p for p, t in files.items() if (not p.exists()) or p.read_text(encoding="utf-8") != t]
        if stale:
            print(f"DOSSIER-CHECK: FAIL ({len(stale)} stale)")
            for p in stale:
                print(f"  stale: {p.relative_to(REPO)}")
            print("  fix: python verification/scripts/build_dossier.py")
            return 1
        print(f"DOSSIER-CHECK: PASS ({len(files)} files)")
        return 0
    for p, t in files.items():
        atomic_write(p, t)
    print(f"DOSSIER: wrote {len(files)} files -> theory/sectors/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
