#!/usr/bin/env python3
"""Build compact reader indexes for large research-management authorities.

The authoritative result, negative-result, gate, roadmap, task, and proof-map
files remain unchanged. These disposable projections provide bounded GitHub and
website entry points without repeating full record bodies.
"""
__version__ = "1.0.0"
__first_issued__ = "2026-08-10"
__version_issued__ = "2026-08-10"

import argparse
import json
import os
import re
import sys
import tempfile
from collections import Counter, defaultdict
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from build_proof_evidence_map import (  # noqa: E402
    load_cards,
    load_events,
    load_explorations,
    load_tasks,
    parse_gate_definitions,
    parse_negatives,
    parse_results,
)

REPO = Path(__file__).resolve().parents[2]
OUTPUTS = {
    "management": REPO / "management" / "INDEX.md",
    "results": REPO / "results" / "INDEX.md",
    "results_json": REPO / "results" / "index.json",
    "negative": REPO / "negative-results" / "INDEX.md",
    "negative_json": REPO / "negative-results" / "index.json",
    "gates": REPO / "claims" / "GATES-INDEX.md",
    "gates_json": REPO / "claims" / "gates-index.json",
    "evidence": REPO / "theory" / "proof-evidence" / "INDEX.md",
}
RECENT_ROWS = 25  # reader-display threshold, not research data
TEXT_LIMIT = 180  # reader-display threshold, not research data
OUTPUT_BYTE_LIMIT = 128 * 1024  # generated landing/locator tooling threshold


def atomic_write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent)); os.close(fd)
    with Path(tmp).open("w", encoding="utf-8", newline="") as stream:
        stream.write(text)
    os.replace(tmp, str(path))


def cell(value, limit=TEXT_LIMIT):
    text = " ".join(str(value or "—").split()).replace("|", "\\|")
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def header(title, authorities):
    sources = ", ".join(f"`{path}`" for path in authorities)
    return [
        f"# {title}", "",
        "<!-- AUTO-GENERATED by verification/scripts/build_management_indexes.py -->",
        "<!-- DO NOT HAND-EDIT. This is a compact reader projection, not an authority. -->",
        "", f"Authorities: {sources}.", "",
    ]


def build():
    cards = load_cards()
    tasks = load_tasks()
    events = load_events()
    explorations = load_explorations()
    results = parse_results()
    negatives = parse_negatives()
    gates = parse_gate_definitions()

    gate_claims = defaultdict(list)
    hypothesis_claims = defaultdict(list)
    for card in cards:
        for gate in card.get("open_gates", []):
            gate_claims[str(gate)].append(str(card["id"]))
        for hypothesis in card.get("hypotheses", []):
            hypothesis_claims[str(hypothesis)].append(str(card["id"]))

    live = [task for task in tasks if task["status"] in {"in_progress", "next", "blocked"}]
    live.sort(key=lambda row: ({"in_progress": 0, "next": 1, "blocked": 2}[row["status"]], row["id"]))

    lines = header("TECT research management index", [
        "claims/*/status.json", "todo/todo.json", "ROADMAP.md",
        "RESULTS-LEDGER.md", "negative-results/registry.md", "claims/GATES.md",
    ])
    tiers = Counter(str(card["tier"]) for card in cards)
    lines.extend([
        f"**{len(cards)} claims** · " + " · ".join(f"{tier}: {tiers[tier]}" for tier in sorted(tiers)),
        f"**{len(results)} reusable results** · **{len(negatives)} negative/audit records** · "
        f"**{len(gates)} registered gates/hypotheses**", "",
        "## Live work", "",
        "| Task | State | Claim | Gate | Task summary |", "|---|---|---|---|---|",
    ])
    for task in live:
        lines.append(
            f"| `{task['id']}` | {cell(task['status'])} | {cell(task.get('claim'))} | "
            f"{cell(task.get('gate'))} | {cell(task.get('title'))} |"
        )
    lines.extend(["", "Full task ledger: [TODO.md](../TODO.md). Detailed staged plan: "
                  "[ROADMAP.md](../ROADMAP.md).", "", "## Most-cited claim-card gates", "",
                  "| Gate | Citing claims |", "|---|---|"])
    for gate, claim_ids in sorted(gate_claims.items(), key=lambda item: (-len(item[1]), item[0]))[:15]:
        lines.append(
            f"| [`{gate}`](../claims/GATES.md#{gate.lower()}) | {cell(', '.join(sorted(claim_ids)))} |"
        )
    lines.extend([
        "", "## Reader routes", "",
        "- [Current claim ledger](../CLAIMS.md)",
        "- [Gate and hypothesis index](../claims/GATES-INDEX.md)",
        "- [Reusable-result index](../results/INDEX.md)",
        "- [Negative/audit index](../negative-results/INDEX.md)",
        "- [Compact proof-evidence entry](../theory/proof-evidence/INDEX.md)",
        "- [Current changelog](../changelog/INDEX.md)",
        "- [Current artefact catalog](../catalog/INDEX.md)", "",
    ])
    management = "\n".join(lines)

    lines = header("Reusable results index", ["RESULTS-LEDGER.md"])
    lines.extend([
        f"**{len(results)} registered results.** Latest {min(RECENT_ROWS, len(results))} are shown; "
        "full statements, boundaries, proof anchors, and publication targets remain in the authority.",
        "", "| ID | Result | Tier/scope |", "|---|---|---|",
    ])
    for result in results[:RECENT_ROWS]:
        tier = result.get("detail", {}).get("tier", "")
        if not tier:
            match = re.search(r"\bT[0-7]\b", str(result.get("summary", "")))
            tier = match.group(0) if match else "See authority"
        display_title = result.get("detail_title") or result["title"]
        lines.append(
            f"| [`{result['id']}`](../RESULTS-LEDGER.md#{result['anchor']}) | "
            f"{cell(display_title)} | {cell(tier)} |"
        )
    lines.extend([
        "", "Search without loading the full ledger:", "", "```bash",
        'rg -n "R-166|keyword" RESULTS-LEDGER.md', "```", "",
        "[Open the full result authority](../RESULTS-LEDGER.md).", "",
    ])
    result_index = "\n".join(lines)

    kinds = Counter(str(row.get("kind", "other")) for row in negatives)
    lines = header("Negative-result and audit index", ["negative-results/registry.md"])
    lines.extend([
        f"**{len(negatives)} registered records** · " + " · ".join(
            f"{kind}: {count}" for kind, count in sorted(kinds.items())
        ), "", f"Latest {min(RECENT_ROWS, len(negatives))} records:", "",
        "| ID | Type | Tested route |", "|---|---|---|",
    ])
    for row in negatives[:RECENT_ROWS]:
        lines.append(
            f"| [`{row['tag']}`](registry.md#{row['anchor']}) | {cell(row.get('kind'))} | "
            f"{cell(row.get('branch'))} |"
        )
    lines.extend([
        "", "Search without loading the full registry:", "", "```bash",
        'rg -n "NG-2026|keyword" negative-results/registry.md', "```", "",
        "[Open the full negative-result authority](registry.md).", "",
    ])
    negative_index = "\n".join(lines)

    missing_status = [gate for gate in gate_claims if not gates.get(gate, {}).get("status_summary")]
    closed_listed = [
        gate for gate in gate_claims
        if str(gates.get(gate, {}).get("status_summary", "")).upper().startswith("CLOSED")
    ]
    lines = header("Gate and hypothesis index", ["claims/GATES.md", "claims/*/status.json"])
    lines.extend([
        f"**{len(gates)} registered definitions** · **{len(gate_claims)} claim-card gate listings** · "
        f"**{len(hypothesis_claims)} live hypothesis listings**.",
        "The tables report claim-card fields exactly; they do not reinterpret registry status.",
        f"Audit flags: {len(missing_status)} listed gate(s) lack an explicit Status field; "
        f"{len(closed_listed)} are still listed by cards although the registry status begins CLOSED.",
        "These source mismatches are preserved for follow-up rather than silently normalized.", "",
        "| Gate | Claims | Current status summary |", "|---|---|---|",
    ])
    for gate, claim_ids in sorted(gate_claims.items(), key=lambda item: item[0]):
        definition = gates.get(gate, {})
        lines.append(
            f"| [`{gate}`](GATES.md#{gate.lower()}) | {cell(', '.join(sorted(claim_ids)))} | "
            f"{cell(definition.get('status_summary') or 'MISSING EXPLICIT STATUS FIELD', 120)} |"
        )
    lines.extend(["", "## Hypotheses cited by live claim cards", "",
                  "| Hypothesis | Claims | Registry statement |", "|---|---|---|"])
    for hypothesis, claim_ids in sorted(hypothesis_claims.items()):
        definition = gates.get(hypothesis, {})
        lines.append(
            f"| [`{hypothesis}`](GATES.md#{hypothesis.lower()}) | "
            f"{cell(', '.join(sorted(claim_ids)))} | "
            f"{cell(definition.get('statement_summary') or 'MISSING DEFINITION', 120)} |"
        )
    lines.extend(["", "[Open the complete gate/hypothesis authority](GATES.md).", ""])
    gate_index = "\n".join(lines)

    verdicts = Counter(str(row["verdict"]) for row in explorations)
    lines = header("Proof-evidence map entry", [
        "theory/proof-evidence-map.md", "verification/proof-evidence-map.json",
    ])
    lines.extend([
        "This page is the bounded starting point. The complete compatibility map remains",
        "available for issued verifiers and deep cross-record searches.", "",
        f"**{len(cards)} claims** · **{len(results)} results** · **{len(negatives)} negatives/audits** · "
        f"**{len(explorations)} proof explorations** · **{len(events)} accepted events**", "",
        "Exploration verdicts: " + " · ".join(
            f"{name}: {count}" for name, count in sorted(verdicts.items())
        ), "", "## Efficient lookup", "",
        "```bash",
        'rg -n "A13|R-166|EXP-000790|gate-id" theory/proof-evidence-map.md',
        "```", "",
        "Start with the [research management index](../../management/INDEX.md), then open",
        "only the linked authority. [Open the complete proof-evidence map](../proof-evidence-map.md).",
        "",
    ])
    evidence_index = "\n".join(lines)

    result_locators = {
        "schema": "tect/results-index/1.0",
        "authority": "RESULTS-LEDGER.md",
        "count": len(results),
        "entries": [
            {"id": row["id"], "title": row["detail_title"] or row["title"],
             "anchor": row["anchor"], "path": "RESULTS-LEDGER.md"}
            for row in results
        ],
    }
    negative_locators = {
        "schema": "tect/negative-index/1.0",
        "authority": "negative-results/registry.md",
        "count": len(negatives),
        "entries": [
            {"id": row["tag"], "kind": row.get("kind", "other"),
             "anchor": row["anchor"], "path": "negative-results/registry.md"}
            for row in negatives
        ],
    }
    gate_locators = {
        "schema": "tect/gate-index/1.0",
        "authority": "claims/GATES.md + claims/*/status.json",
        "count": len(gates),
        "entries": [
            {"id": identifier, "anchor": identifier.lower(), "path": "claims/GATES.md",
             "gate_claim_ids": sorted(gate_claims.get(identifier, [])),
             "hypothesis_claim_ids": sorted(hypothesis_claims.get(identifier, [])),
             "has_explicit_status": bool(definition.get("status_summary"))}
            for identifier, definition in sorted(gates.items())
        ],
    }
    assert len({row["id"] for row in result_locators["entries"]}) == len(results)
    assert len({row["id"] for row in negative_locators["entries"]}) == len(negatives)
    assert len({row["id"] for row in gate_locators["entries"]}) == len(gates)

    outputs = {
        OUTPUTS["management"]: management,
        OUTPUTS["results"]: result_index,
        OUTPUTS["results_json"]: json.dumps(result_locators, indent=2, ensure_ascii=False) + "\n",
        OUTPUTS["negative"]: negative_index,
        OUTPUTS["negative_json"]: json.dumps(negative_locators, indent=2, ensure_ascii=False) + "\n",
        OUTPUTS["gates"]: gate_index,
        OUTPUTS["gates_json"]: json.dumps(gate_locators, indent=2, ensure_ascii=False) + "\n",
        OUTPUTS["evidence"]: evidence_index,
    }
    oversized = [path for path, text in outputs.items()
                 if len(text.encode("utf-8")) > OUTPUT_BYTE_LIMIT]
    if oversized:
        raise ValueError(f"management index exceeds {OUTPUT_BYTE_LIMIT} bytes: {oversized}")
    return outputs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = build()
    if args.check:
        stale = [path for path, expected in outputs.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != expected]
        print(f"MANAGEMENT-INDEX-CHECK: {'PASS' if not stale else 'FAIL'}")
        for path in stale:
            print(f"  - {path.relative_to(REPO)}")
        return 0 if not stale else 1
    for path, text in outputs.items():
        atomic_write(path, text)
    print(f"MANAGEMENT-INDEX: wrote {len(outputs)} compact reader surfaces")
    return 0


if __name__ == "__main__":
    sys.exit(main())
