"""build_lineage.py — generate per-claim theory-development lineage ledgers.

Verification-first development trace: every claim's notes/ + runs/ are parsed
from their standard banners (Title / Claim / Version two-date / Status /
revision-history) and emitted as claims/<ID>/LINEAGE.md — an ORDERED
(chronological + supersession-resolved) record of how the theory for that
claim developed. A curated narrative overlay (claims/<ID>/lineage-narrative.md,
hand-written, optional) is included verbatim at the top so the editorial arc
("why each step mattered") lives beside the auto-built timeline.

GENERATED FILE — never hand-edit claims/<ID>/LINEAGE.md. Edit the narrative
overlay instead, then regenerate. Run after any notes/ or runs/ change:
    python verification/scripts/build_lineage.py            # all claims
    python verification/scripts/build_lineage.py --check    # CI staleness gate
"""
__version__ = "1.0.0"
__first_issued__ = "2026-06-06"
__version_issued__ = "2026-06-06"

import re, sys, json
from pathlib import Path
from datetime import datetime

REPO = Path(__file__).resolve().parents[2]
CLAIMS = REPO / "claims"

BANNER = {k: re.compile(rf"^%\s*{k}:\s*(.+)$", re.M) for k in ("Title", "Claim", "Version", "Status")}
SUPER = re.compile(r"^%\s*SUPERSEDED by\s+(\S+)")
VER_DATES = re.compile(r"v([\d.]+)\s*--\s*first issued\s*([\d-]+);\s*this version issued\s*([\d-]+)")
REVHIST = re.compile(r"^%\s+v([\d.]+)\s*\(([\d-]+)\)\s*(.+?)\s*$", re.M)
# lineage slug = filename minus -YYMMDD[-YYMMDD]-vN.M.tex.txt
SLUG = re.compile(r"^(.*?)-\d{6}(?:-\d{6})?-v[\d.]+\.tex\.txt$")


def parse_note(p):
    t = p.read_text(encoding="utf-8")
    superseded = bool(SUPER.search(t.splitlines()[0])) if t else False
    def g(k):
        m = BANNER[k].search(t); return m.group(1).strip() if m else ""
    ver = g("Version"); vm = VER_DATES.search(ver)
    first, cur, vnum = ("", "", "")
    if vm:
        vnum, first, cur = vm.group(1), vm.group(2), vm.group(3)
    sm = SLUG.match(p.name); slug = sm.group(1) if sm else p.stem
    revs = [(v, d, txt) for v, d, txt in REVHIST.findall(t)]
    return dict(path=p.name, slug=slug, title=g("Title"), status=g("Status"),
                vnum=vnum, first=first, cur=cur, superseded=superseded, revs=revs)


def tier_of(status):
    m = re.search(r"\b(T[0-7])\b", status)
    return m.group(1) if m else (("DRAFT" if "DRAFT" in status.upper() else
            "PROPOSAL" if "PROPOSAL" in status.upper() else
            "AUDIT" if "AUDIT" in status.upper() else "—"))


def narrative_block(cid):
    f = CLAIMS / cid / "lineage-narrative.md"
    if f.exists():
        return f.read_text(encoding="utf-8").rstrip() + "\n"
    return ("_No curated narrative yet. Write `claims/%s/lineage-narrative.md` "
            "(the editorial development arc) and regenerate._\n" % cid)


def build_one(cid):
    cdir = CLAIMS / cid
    # gather notes from the flat notes/ AND any sub-proof <sub>/notes/ folders
    items = []  # (subproof_name, parsed_note)
    if (cdir / "notes").exists():
        for q in sorted((cdir / "notes").glob("*.tex.txt")):
            items.append(("", parse_note(q)))
    for q in sorted(cdir.glob("*/notes/*.tex.txt")):
        items.append((q.parent.parent.name, parse_note(q)))
    has_sub = any(sp for sp, _ in items)
    notes = [n for _, n in items]
    # group by subproof -> slug -> versions
    groups = {}
    for sp, n in items:
        groups.setdefault(sp, {}).setdefault(n["slug"], []).append(n)

    def lineage_rows(lin):
        rows = []
        for slug, vs in lin.items():
            vs.sort(key=lambda x: (x["first"], x["vnum"]))
            current = [v for v in vs if not v["superseded"]]
            cur = current[-1] if current else vs[-1]
            rows.append(dict(slug=slug, first=vs[0]["first"] or "?", cur=cur, versions=vs))
        rows.sort(key=lambda r: (r["first"], r["slug"]))
        return rows

    sj = {}
    sjf = cdir / "status.json"
    if sjf.exists():
        try: sj = json.loads(sjf.read_text(encoding="utf-8"))
        except Exception: sj = {}
    runs = sorted([d.name for d in (cdir / "runs").glob("*")]) if (cdir / "runs").exists() else []
    total_lineages = sum(len(g) for g in groups.values())

    L = []
    L.append(f"# Development lineage — {cid}")
    L.append("")
    L.append(f"**Claim**: {sj.get('title','(title in status.json)')}  ")
    L.append(f"**Current tier**: {sj.get('tier','—')} ({sj.get('lifecycle','')})  ")
    sub_summary = ""
    if has_sub:
        sub_summary = "  ·  **Sub-proofs**: " + ", ".join(
            f"{sp} ({len(groups[sp])})" for sp in sorted(groups) if sp)
    L.append(f"**Notes**: {len(notes)} files / {total_lineages} note-lineages{sub_summary}  ·  "
             f"**Runs**: {len(runs)}  ·  generated by `build_lineage.py` v{__version__}")
    L.append("")
    L.append("> GENERATED FILE — do not hand-edit. Edit "
             f"`claims/{cid}/lineage-narrative.md` (curated arc) and regenerate.")
    L.append("")
    L.append("## Development arc (curated)")
    L.append("")
    L.append(narrative_block(cid))
    L.append("## Chronological note-lineage (auto)")
    L.append("")
    sp_order = sorted([sp for sp in groups if sp]) + ([""] if "" in groups else [])
    all_rows = []
    for sp in sp_order:
        rows = lineage_rows(groups[sp])
        all_rows.extend(rows)
        if has_sub:
            L.append(f"### {sp + '/' if sp else '(unfiled — claim root)'}")
            L.append("")
        L.append("| # | First issued | Cur. | Note (current title) | Status/tier | Versions |")
        L.append("|---|---|---|---|---|---|")
        for i, r in enumerate(rows, 1):
            cur = r["cur"]
            vchain = " → ".join(f"v{v['vnum']}{'†' if v['superseded'] else ''}" for v in r["versions"])
            title = (cur["title"] or r["slug"])[:78].replace("|", "\\|")
            L.append(f"| {i} | {r['first']} | v{cur['vnum']} | {title} | {tier_of(cur['status'])} | {vchain} |")
        L.append("")
    L.append("† = superseded version (kept on disk, immutable, forward-pointer at top).")
    L.append("")
    L.append("## Per-note revision history (auto)")
    L.append("")
    for r in all_rows:
        cur = r["cur"]
        L.append(f"### {r['slug']}  ·  current `{cur['path']}`")
        L.append("")
        allrevs = {}
        for v in r["versions"]:
            for vn, dt, txt in v["revs"]:
                allrevs[vn] = (dt, txt)
        for vn in sorted(allrevs, key=lambda s: [int(x) for x in s.split(".")]):
            dt, txt = allrevs[vn]
            txt = re.sub(r"\s+", " ", txt).strip()
            L.append(f"- **v{vn}** ({dt}) {txt}")
        L.append("")
    if runs:
        L.append("## Run artefacts")
        L.append("")
        for rn in runs:
            L.append(f"- `runs/{rn}/`")
        L.append("")
    L.append(f"<!-- generated {datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')} -->")
    return "\n".join(L) + "\n"

def main():
    check = "--check" in sys.argv
    claims = sorted([d.name for d in CLAIMS.iterdir()
                     if d.is_dir() and not d.name.startswith("_")])
    stale = []
    for cid in claims:
        content = build_one(cid)
        out = CLAIMS / cid / "LINEAGE.md"
        old = out.read_text(encoding="utf-8") if out.exists() else ""
        # ignore the trailing generated-timestamp line for staleness
        norm = lambda s: re.sub(r"<!-- generated.*?-->", "", s)
        if norm(old) != norm(content):
            if check:
                stale.append(cid)
            else:
                import tempfile, os
                fd, tmp = tempfile.mkstemp(dir=str(out.parent))
                with os.fdopen(fd, "w", encoding="utf-8") as f: f.write(content)
                os.replace(tmp, str(out))
    if check:
        if stale:
            print(f"LINEAGE-CHECK: FAIL (stale: {', '.join(stale)})"); return 1
        print("LINEAGE-CHECK: PASS"); return 0
    print(f"LINEAGE: regenerated {len(claims)} claim ledgers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
